### ISSUE TITLE
Project cannot compile

### ISSUE THREAD

**Issue by gembin** [dpettigrew/Artisan#1]
The project cannot compile, it has 45 issues.  I'm using xcode 6.2

e.g. errors:
...
Artisan/src/Artisan.swift:355:125: Type of expression is ambiguous without more context
Artisan/src/Artisan.swift:127:13: Use of unresolved identifier 'ellipse_'
Artisan/src/Artisan.swift:172:62: Use of unresolved identifier 'rectangle'
Artisan/src/Artisan.swift:355:125: Braced block of statements is an unused closure
...

**Comment by dpettigrew** [comment]
The code has been update for Swift 2.1 and Xcode 7.2 if you want to try again.
